version: '3'

volumes:
  microservice_app_data:

services:
  api-gateway:
    image: api-gateway
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/api-gateway/src:/url/src/app/src:z
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WORK_ENV=local
      - POSTGRES_MASTER_HOST=host.docker.internal
    restart: "no"
  user-service:
    image: user-service
    build:
      context: ./apps/user
      dockerfile: Dockerfile
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./apps/user/src:/usr/src/app/src:z
    environment:
      - PORT=3001
      - WORK_ENV=local
      - POSTGRES_MASTER_HOST=host.docker.internal
    restart: "no"