version: "3.8"

services:
  db:
    image: postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "12345:5432"
    container_name: master
    environment:
      - POSTGRES_MASTER_DB=master
      - POSTGRES_MASTER_USERNAME=master_user
      - POSTGRES_MASTER_PASSWORD=master1234
      - POSTGRES_MASTER_INITDB_ARGS=--encoding=UTF-8
    restart: always
  db_slave:
    image: postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "12346:5432"
    container_name: slave
    environment:
      - POSTGRES_SLAVE_DB=slave
      - POSTGRES_SLAVE_USERNAME=slave_user
      - POSTGRES_SLAVE_PASSWORD=slave1234
      - POSTGRES_SLAVE_INITDB_ARGS=--encoding=UTF-8
    restart: always